version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: servidor_web
    ports:
      - "7080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - red_web



  api:
    build: ./api
    container_name: api_codificacion
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./api/app:/app
    networks:
      - red_web

networks:
  red_web:
    driver: bridge
