version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: servidor_web
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - red_web



  api:
    build: ./api
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./api/app:/app



networks:
  red_web:
    driver: bridge
