version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: servidor_web
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - red_web

networks:
  red_web:
    driver: bridge
